from tkinter import *
root=Tk()
root.title("login app")
root.geometry("400x400")
frame=Frame(master=root,relief=RAISED,borderwidth=1,height=200,width=360,bg="lightblue")
lb1=Label(frame,text="full name",bg="lightblue",fg="black",width=12)
lb2=Label(frame,text="email id",bg="lightblue",fg="black",width=12)
lb3=Label(frame,text="password",bg="lightblue",fg="black",width=12)
name_entry=Entry(frame)
email_entry=Entry(frame)
password_entry=Entry(frame,show="*")
def display():
    name=name_entry.get()
    greet="hello "+name
    message= "\n congratulations! you have successfully logged in"
    text_box.insert(END,greet)
    text_box.insert(END,message)
text_box=Text(bg="blue",fg="white")
btn=Button(text="create account",command=display,bg="yellow")
frame.place(x=20,y=0)
lb1.place(x=20,y=20)
name_entry.place(x=150,y=20)
lb2.place(x=20,y=80)
email_entry.place(x=150,y=80)
lb3.place(x=20,y=140)
password_entry.place(x=150,y=140)
btn.place(x=130,y=210)
text_box.place(y=250)
root.mainloop()