from tkinter import *
window=Tk()
window.title("getting started with widgets")
window.geometry("400x300")
lb1=Label(text="This App will display the product of your entered numbers",fg="white",bg="blue",height=1,width=300)
num1lb=Label(text="Enter first number",bg="blue")
num1entry=Entry()
num2lb=Label(text="Enter second number",bg="blue")
num2entry=Entry()
def display():
    num1=int(num1entry.get())
    num2=int(num2entry.get())
    product=num1*num2
    result="The product of "+str(num1)+" and "+str(num2)+" is: "+str(product)
    text_box.insert(END,result)
text_box=Text(height=3)
btn=Button(text="Calculate Product",command=display , height=1,width=20,bg="blue",fg="white")
lb1.pack()
num1lb.pack()
num1entry.pack()
num2lb.pack()
num2entry.pack()
btn.pack()
text_box.pack()
window.mainloop()